# Generated by Django 4.1.7 on 2023-03-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_text',
        ),
    ]
