# Generated by Django 4.1.5 on 2023-03-05 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_id',
        ),
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, related_name='Resume', to='resumes_rest.jobappsvo'),
            preserve_default=False,
        ),
    ]
