# Generated by Django 4.1.5 on 2023-03-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.BinaryField(default=1),
            preserve_default=False,
        ),
    ]
