# Generated by Django 4.1.5 on 2023-03-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_rest', '0002_remove_resume_job_id_resume_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='exp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='reason',
            field=models.TextField(default='love this job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='skill',
            field=models.CharField(default='python, react, etc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='value',
            field=models.TextField(default='teamwork and communication'),
            preserve_default=False,
        ),
    ]
