# Generated by Django 4.1.5 on 2023-03-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_rest', '0002_remove_resume_job_id_resume_job'),
        ('resumes_rest', '0002_resume_file'),
    ]

    operations = [
    ]
