# Generated by Django 4.1.5 on 2023-03-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_rest', '0003_resume_exp_resume_reason_resume_skill_resume_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
