# Generated by Django 4.1.5 on 2023-03-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_rest', '0004_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('resume_text', models.TextField()),
            ],
        ),
    ]
