# Generated by Django 4.1.5 on 2023-03-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAppsVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
